name: Deploy
on:
  push:
    branches:
    - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: source ./create-zip.sh

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v17
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: oneQshop-v0
        environment_name: Oneqshopv0-env
        version_label: oneqshop-v0-source-v1.5
        region: ap-south-1
        deployment_package: deploy.zip
